import type { Metadata } from "next";
import "./globals.css";


// const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Aplication Cash",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            
            <body
                className="bg-gray-100 text-gray-900 font-sans"
            >
                {children}
            </body>
        </html>
    );
}
